# Generated by Django 4.2.15 on 2024-09-02 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScannedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to='scanned_images/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('color_mode', models.CharField(max_length=20)),
                ('zoom_level', models.IntegerField()),
                ('page_number', models.PositiveIntegerField()),
            ],
        ),
    ]
