# Generated by Django 4.2.15 on 2024-09-02 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scannerApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scannedimage',
            name='uploaded_at',
        ),
        migrations.AlterField(
            model_name='scannedimage',
            name='file',
            field=models.FileField(upload_to='temp_scans/'),
        ),
        migrations.AlterField(
            model_name='scannedimage',
            name='page_number',
            field=models.IntegerField(),
        ),
    ]
